import { useMemo, useState } from 'react';
import {
  Activity, AlertTriangle, Archive, BarChart3, Bell, Bot, Box, CalendarDays, Check, ChevronDown,
  ChevronLeft, ChevronRight, CircleHelp, ClipboardCheck, Clock3, Cloud, CloudOff, Download, FileBarChart,
  Filter, Gauge, HardHat, LayoutDashboard, ListFilter, MapPin, Menu, MessageSquareText, MoreHorizontal,
  Package, PanelLeftClose, Plus, Search, Settings, ShieldCheck, SlidersHorizontal, Sparkles, Timer,
  Users, Wrench, X, Zap
} from 'lucide-react';

type Page = 'dashboard'|'orders'|'assets'|'handover'|'schedule'|'indicators'|'reports'|'alerts'|'ai'|'users'|'settings'|'field';
type Order = { id:string; asset:string; tag:string; service:string; area:string; priority:'Crítica'|'Alta'|'Média'|'Baixa'; status:string; owner:string; due:string; progress:number };

const orders: Order[] = [
  {id:'OM-2026-1548',asset:'Bomba centrífuga',tag:'BOM-1234A',service:'Substituição do selo mecânico',area:'Mecânica',priority:'Alta',status:'Em execução',owner:'João Silva',due:'Hoje, 14:30',progress:68},
  {id:'OM-2026-1552',asset:'Correia transportadora',tag:'CT-07B',service:'Inspeção e ajuste de alinhamento',area:'Mecânica',priority:'Crítica',status:'Atrasada',owner:'Marcos Rocha',due:'Hoje, 10:00',progress:35},
  {id:'OM-2026-1541',asset:'Painel elétrico QGBT',tag:'QGBT-02',service:'Termografia e reaperto geral',area:'Elétrica',priority:'Média',status:'Programada',owner:'Ana Costa',due:'Amanhã, 08:00',progress:0},
  {id:'OM-2026-1537',asset:'Compressor de ar',tag:'COM-04',service:'Troca de filtros e lubrificante',area:'Mecânica',priority:'Baixa',status:'Aguard. material',owner:'Paulo Reis',due:'02 set, 09:00',progress:20},
  {id:'OM-2026-1529',asset:'Sensor de nível',tag:'LSH-224',service:'Calibração de instrumento',area:'Instrumentação',priority:'Alta',status:'Validação',owner:'Beatriz Lima',due:'31 ago, 16:00',progress:100},
];

const nav = [
  {section:'VISÃO GERAL', items:[['dashboard','Dashboard',LayoutDashboard],['alerts','Central de alertas',Bell]]},
  {section:'MANUTENÇÃO', items:[['orders','Ordens de manutenção',Wrench],['assets','Gestão de ativos',Box],['schedule','Programação semanal',CalendarDays]]},
  {section:'OPERAÇÃO', items:[['handover','Passagem de turno',ClipboardCheck],['field','Operação em campo',HardHat]]},
  {section:'ANÁLISE', items:[['indicators','Indicadores',BarChart3],['reports','Relatórios',FileBarChart],['ai','IA de manutenção',Sparkles]]},
  {section:'GESTÃO', items:[['users','Usuários e acessos',Users],['settings','Configurações',Settings]]},
] as const;

const pageNames:Record<Page,string>={dashboard:'Visão operacional',orders:'Ordens de manutenção',assets:'Gestão de ativos',handover:'Passagem de turno',schedule:'Programação semanal',indicators:'Indicadores de manutenção',reports:'Relatórios',alerts:'Central de alertas',ai:'IA de manutenção',users:'Usuários e acessos',settings:'Configurações',field:'Operação em campo'};

function Logo(){return <div className="logo"><div className="logoMark"><span/><span/><span/></div><div><strong>NEXUM</strong><small>MAINTENANCE HUB</small></div></div>}
function Status({children}:{children:string}){const cls=children.toLowerCase().replaceAll(' ','-').replace('.','');return <span className={`status ${cls}`}><i/>{children}</span>}
function Priority({value}:{value:Order['priority']}){return <span className={`priority ${value.toLowerCase()}`}>{value}</span>}

function Sidebar({page,setPage,open,setOpen}:{page:Page,setPage:(p:Page)=>void,open:boolean,setOpen:(v:boolean)=>void}){
 return <aside className={`sidebar ${open?'open':''}`}><div className="brand"><Logo/><button onClick={()=>setOpen(false)}><PanelLeftClose size={18}/></button></div><div className="siteSelect"><MapPin size={16}/><div><small>UNIDADE ATUAL</small><b>Terminal Sudeste</b></div><ChevronDown size={15}/></div><nav>{nav.map(g=><div className="navGroup" key={g.section}><label>{g.section}</label>{g.items.map(([id,label,Icon])=><button className={page===id?'active':''} key={id} onClick={()=>{setPage(id as Page);setOpen(false)}}><Icon size={18}/><span>{label}</span>{id==='alerts'&&<em>5</em>}</button>)}</div>)}</nav><div className="sidebarFoot"><div className="sync"><Cloud size={16}/><div><b>Sistema sincronizado</b><small>há 2 minutos</small></div><span/></div><button className="profile"><div className="avatar">CS</div><div><b>Carlos Santos</b><small>Supervisor de manutenção</small></div><MoreHorizontal size={17}/></button></div></aside>
}

function Header({page,onMenu}:{page:Page,onMenu:()=>void}){return <header><button className="mobileMenu" onClick={onMenu}><Menu/></button><div><div className="crumb">Nexum <ChevronRight size={13}/> {pageNames[page]}</div><h1>{pageNames[page]}</h1></div><div className="headActions"><div className="globalSearch"><Search size={17}/><input placeholder="Buscar ordens, ativos, TAGs..."/><kbd>⌘ K</kbd></div><button className="iconBtn hasDot"><Bell size={19}/><i/></button><button className="help"><CircleHelp size={17}/> Central de ajuda</button></div></header>}

function Metric({label,value,unit,delta,good=true,icon:Icon}:{label:string,value:string,unit?:string,delta:string,good?:boolean,icon:any}){return <div className="metric card"><div className="metricTop"><span>{label}</span><div><Icon size={18}/></div></div><div className="metricValue">{value}<small>{unit}</small></div><div className={`delta ${good?'good':'bad'}`}><b>{good?'↗':'↘'} {delta}</b><span>vs. mês anterior</span></div><div className="spark"><i/><i/><i/><i/><i/><i/><i/><i/></div></div>}

function Donut(){return <div className="donutWrap"><div className="donut"><div><b>248</b><span>Total</span></div></div><div className="legend"><p><i className="c1"/>Em execução <b>64</b></p><p><i className="c2"/>Programadas <b>82</b></p><p><i className="c3"/>Aguardando <b>46</b></p><p><i className="c4"/>Encerradas <b>56</b></p></div></div>}
function TrendChart(){return <div className="trendChart"><div className="chartY"><span>100%</span><span>90%</span><span>80%</span><span>70%</span></div><svg viewBox="0 0 650 180" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#e7a72d" stopOpacity=".25"/><stop offset="1" stopColor="#e7a72d" stopOpacity="0"/></linearGradient></defs><path className="grid" d="M0 20H650M0 70H650M0 120H650M0 170H650"/><path className="target" d="M0 55H650"/><path className="area" d="M0 135 C55 115 80 128 125 105 S210 80 250 92 S330 55 375 70 S455 45 500 55 S590 28 650 35 L650 180L0 180Z"/><path className="line" d="M0 135 C55 115 80 128 125 105 S210 80 250 92 S330 55 375 70 S455 45 500 55 S590 28 650 35"/></svg><div className="chartX"><span>Mar</span><span>Abr</span><span>Mai</span><span>Jun</span><span>Jul</span><span>Ago</span></div></div>}

function Dashboard({setPage}:{setPage:(p:Page)=>void}){return <><section className="heroRow"><div><p className="eyebrow">SEGUNDA-FEIRA, 31 DE AGOSTO</p><h2>Bom dia, Carlos.</h2><p>Veja o panorama da operação no Terminal Sudeste.</p></div><div className="filters"><button><CalendarDays size={16}/> Últimos 30 dias <ChevronDown size={15}/></button><button><MapPin size={16}/> Todas as áreas <ChevronDown size={15}/></button><button className="filterBtn"><SlidersHorizontal size={16}/></button></div></section><section className="metrics"><Metric label="Disponibilidade" value="94,8" unit="%" delta="2,4%" icon={Gauge}/><Metric label="Aderência semanal" value="91,2" unit="%" delta="4,1%" icon={ClipboardCheck}/><Metric label="MTBF" value="186" unit="h" delta="8,6%" icon={Activity}/><Metric label="MTTR" value="3,4" unit="h" delta="0,7h" good={false} icon={Timer}/><Metric label="Backlog" value="3,2" unit="sem" delta="0,4 sem" icon={Archive}/></section><section className="dashboardGrid"><div className="card panel trendPanel"><div className="panelHead"><div><h3>Tendência de disponibilidade</h3><p>Desempenho dos ativos nos últimos 6 meses</p></div><div className="chartLegend"><span><i/>Real</span><span><i/>Meta 95%</span></div></div><TrendChart/></div><div className="card panel"><div className="panelHead"><div><h3>Ordens por status</h3><p>Distribuição no período</p></div><button className="dots"><MoreHorizontal/></button></div><Donut/></div></section><section className="bottomGrid"><div className="card panel"><div className="panelHead"><div><h3>Ordens que exigem atenção</h3><p>Priorizadas por criticidade e prazo</p></div><button className="link" onClick={()=>setPage('orders')}>Ver todas <ChevronRight size={15}/></button></div><OrderTable compact/></div><div className="card panel alertsPanel"><div className="panelHead"><div><h3>Alertas operacionais</h3><p>Atualizados em tempo real</p></div><button className="link" onClick={()=>setPage('alerts')}>Ver central</button></div><div className="alertItem critical"><AlertTriangle/><div><b>Correia CT-07B parada</b><p>OM crítica atrasada há 4 horas</p><small>há 12 min · Mecânica</small></div><ChevronRight/></div><div className="alertItem warning"><Clock3/><div><b>Preventiva próxima do prazo</b><p>3 atividades vencem nas próximas 24h</p><small>há 36 min · Planejamento</small></div><ChevronRight/></div><div className="alertItem info"><Activity/><div><b>MTTR acima da meta</b><p>Britagem registrou aumento de 18%</p><small>há 1h · Indicadores</small></div><ChevronRight/></div></div></section></>}

function OrderTable({compact=false,onSelect}:{compact?:boolean,onSelect?:(o:Order)=>void}){const rows=compact?orders.slice(0,3):orders;return <div className="tableWrap"><table><thead><tr><th>ORDEM</th><th>ATIVO / SERVIÇO</th>{!compact&&<th>ÁREA</th>}<th>PRIORIDADE</th><th>STATUS</th>{!compact&&<th>RESPONSÁVEL</th>}<th>PRAZO</th><th/></tr></thead><tbody>{rows.map(o=><tr key={o.id} onClick={()=>onSelect?.(o)}><td><b className="orderId">{o.id}</b></td><td><b>{o.tag} · {o.asset}</b><small>{o.service}</small></td>{!compact&&<td>{o.area}</td>}<td><Priority value={o.priority}/></td><td><Status>{o.status}</Status></td>{!compact&&<td><span className="owner"><i>{o.owner.split(' ').map(x=>x[0]).join('').slice(0,2)}</i>{o.owner}</span></td>}<td><b className={o.status==='Atrasada'?'dangerText':''}>{o.due}</b></td><td><ChevronRight size={16}/></td></tr>)}</tbody></table></div>}

function Orders(){const [selected,setSelected]=useState<Order|null>(null);const [toast,setToast]=useState(false);return <><PageIntro text="Planeje, acompanhe e execute intervenções em todos os ativos."><button className="secondary"><Download size={16}/> Exportar</button><button className="primary" onClick={()=>{setToast(true);setTimeout(()=>setToast(false),2500)}}><Plus size={17}/> Nova ordem</button></PageIntro><div className="quickStats"><div><span>ABERTAS</span><b>38</b><small>+6 esta semana</small></div><div><span>EM EXECUÇÃO</span><b>24</b><small>9 dentro do prazo</small></div><div><span>AGUARDANDO</span><b>17</b><small>6 aguardam material</small></div><div><span>CRÍTICAS</span><b className="dangerText">7</b><small>2 atrasadas</small></div></div><div className="card tableCard"><div className="tableTools"><div className="tabs"><button className="active">Todas <i>248</i></button><button>Abertas <i>38</i></button><button>Em execução <i>24</i></button><button>Programadas <i>82</i></button><button>Encerradas</button></div><div className="tools"><div className="inlineSearch"><Search size={16}/><input placeholder="Buscar ordem ou ativo"/></div><button><Filter size={16}/> Filtros <i>2</i></button></div></div><OrderTable onSelect={setSelected}/><div className="pagination"><span>Mostrando 1–5 de 248 ordens</span><div><button><ChevronLeft/></button><button className="active">1</button><button>2</button><button>3</button><span>...</span><button>50</button><button><ChevronRight/></button></div></div></div>{selected&&<OrderDrawer order={selected} onClose={()=>setSelected(null)}/>} {toast&&<div className="toast"><Check size={18}/> Formulário de nova ordem iniciado</div>}</>}

function OrderDrawer({order,onClose}:{order:Order,onClose:()=>void}){return <div className="overlay" onClick={onClose}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawerHead"><div><span>ORDEM DE MANUTENÇÃO</span><h2>{order.id}</h2></div><button onClick={onClose}><X/></button></div><div className="drawerStatus"><Status>{order.status}</Status><Priority value={order.priority}/></div><div className="assetHero"><div className="assetIcon"><Wrench/></div><div><small>ATIVO</small><h3>{order.tag} · {order.asset}</h3><p><MapPin size={14}/> Terminal Sudeste · {order.area}</p></div></div><section className="drawerSection"><label>SERVIÇO</label><h3>{order.service}</h3><p>Executar intervenção conforme plano de manutenção, com bloqueio do equipamento e registro de evidências antes e depois.</p></section><div className="detailGrid"><div><span>Responsável</span><b>{order.owner}</b></div><div><span>Prazo</span><b>{order.due}</b></div><div><span>Tempo estimado</span><b>04h 30min</b></div><div><span>Centro de trabalho</span><b>MAN-01</b></div></div><section className="drawerSection"><div className="progressTitle"><label>PROGRESSO DA EXECUÇÃO</label><b>{order.progress}%</b></div><div className="progress"><i style={{width:`${order.progress}%`}}/></div></section><section className="timeline"><h3>Histórico recente</h3><div><i/><p><b>Execução atualizada</b><span>{order.owner} · há 38 minutos</span></p></div><div><i/><p><b>Checklist de segurança concluído</b><span>Equipe de campo · hoje, 09:42</span></p></div><div><i/><p><b>Ordem programada</b><span>Planejamento · 29 ago, 16:08</span></p></div></section><div className="drawerActions"><button className="secondary">Ver detalhes completos</button><button className="primary">Atualizar ordem</button></div></aside></div>}

function PageIntro({text,children}:{text:string,children?:any}){return <section className="pageIntro"><p>{text}</p><div>{children}</div></section>}
function Assets(){const assets=[['CT-07B','Correia transportadora 07','Transportadores','Indisponível','Crítica','há 2 dias'],['BOM-1234A','Bomba centrífuga principal','Bombas','Em manutenção','Alta','há 18 dias'],['COM-04','Compressor de ar 04','Compressores','Operacional','Alta','há 31 dias'],['QGBT-02','Painel elétrico geral BT','Painéis elétricos','Operacional','Crítica','há 12 dias'],['EMP-02','Empilhadeira de minério','Máquinas móveis','Operacional','Média','há 45 dias']];return <><PageIntro text="Monitore a saúde e o histórico de 1.284 ativos cadastrados."><button className="secondary"><Download size={16}/> Importar</button><button className="primary"><Plus size={17}/> Novo ativo</button></PageIntro><div className="assetStats"><div><Box/><span><b>1.284</b>Ativos cadastrados</span></div><div><Check/><span><b>1.196</b>Operacionais</span></div><div className="warn"><Wrench/><span><b>72</b>Em manutenção</span></div><div className="crit"><AlertTriangle/><span><b>16</b>Indisponíveis</span></div></div><div className="card tableCard"><div className="tableTools"><div className="inlineSearch wide"><Search/><input placeholder="Buscar por TAG, nome ou categoria..."/></div><div className="tools"><button><ListFilter/> Categoria</button><button><MapPin/> Localização</button><button><Activity/> Status</button></div></div><div className="tableWrap"><table><thead><tr><th>TAG / ATIVO</th><th>CATEGORIA</th><th>STATUS</th><th>CRITICIDADE</th><th>ÚLTIMA MANUTENÇÃO</th><th>SAÚDE</th><th/></tr></thead><tbody>{assets.map((a,i)=><tr key={a[0]}><td><b className="orderId">{a[0]}</b><small>{a[1]}</small></td><td>{a[2]}</td><td><Status>{a[3]}</Status></td><td><span className={`criticality c${i%3}`}>{a[4]}</span></td><td>{a[5]}</td><td><div className="health"><span><i style={{width:`${[32,61,92,87,96][i]}%`}}/></span><b>{[32,61,92,87,96][i]}%</b></div></td><td><ChevronRight/></td></tr>)}</tbody></table></div></div></>}

function Handover(){return <><PageIntro text="Garanta continuidade, segurança e rastreabilidade entre as equipes."><button className="primary"><Plus/> Nova passagem</button></PageIntro><div className="handoverHero card"><div><p>TURNO ATUAL</p><h2>Turno A · 06:00–14:00</h2><span><span className="liveDot"/> Em andamento · encerra em 2h 18min</span></div><div className="shiftTeam"><div className="avatars"><i>CS</i><i>JS</i><i>AC</i><i>+6</i></div><span><b>Carlos Santos</b>Responsável pelo turno</span></div><button className="secondary">Encerrar e passar turno <ChevronRight/></button></div><div className="handoverGrid"><div className="card handoverForm"><div className="panelHead"><div><h3>Registro do turno</h3><p>Terminal Sudeste · Área operacional</p></div><span className="draft">Rascunho salvo</span></div>{[['O que aconteceu?','Descreva ocorrências, anomalias e eventos relevantes do turno...'],['O que foi feito?','Registre as intervenções e decisões tomadas pela equipe...'],['O que ficou pendente?','Liste atividades e ações que precisam de continuidade...'],['O que o próximo turno precisa saber?','Destaque riscos, bloqueios e orientações importantes...']].map((x,i)=><label className="textField" key={x[0]}><span><i>{i+1}</i>{x[0]}</span><textarea placeholder={x[1]} defaultValue={i===0?'Parada da correia CT-07B às 08:14 por desalinhamento. Área isolada e manutenção acionada.':''}/></label>)}<div className="formActions"><button className="secondary">Salvar rascunho</button><button className="primary"><ShieldCheck/> Revisar e enviar</button></div></div><div><div className="card pending"><div className="panelHead"><div><h3>Pendências abertas</h3><p>Itens que precisam de acompanhamento</p></div><b>4</b></div>{['Alinhamento da correia CT-07B','Validar teste do sensor LSH-224','Liberar bloqueio da área 3','Receber rolamento 22318'].map((x,i)=><div className="pendingItem"><span className={i===0?'critical':''}><Clock3/></span><div><b>{x}</b><small>{i<2?'Prioridade alta':'Prioridade média'} · Turno A</small></div><ChevronRight/></div>)}</div><div className="card lastHandover"><h3>Última passagem recebida</h3><p>Turno C · 22:00–06:00</p><div className="readConfirm"><Check/><div><b>Lida e confirmada</b><small>por Carlos Santos às 05:54</small></div></div><button>Ver passagem completa</button></div></div></div></>}

function Schedule(){const days=['SEG 31','TER 01','QUA 02','QUI 03','SEX 04'];return <><PageIntro text="Distribua a carga de trabalho e acompanhe a aderência semanal."><button className="secondary"><ChevronLeft/> Semana 36 <ChevronRight/></button><button className="primary"><Plus/> Programar atividade</button></PageIntro><div className="scheduleStats"><div><b>42</b><span>Atividades planejadas</span></div><div><b>128h</b><span>Carga programada</span></div><div><b>91,2%</b><span>Aderência prevista</span></div><div><b>6</b><span>Equipes mobilizadas</span></div></div><div className="card kanban"><div className="weekHeader"><div>CALENDÁRIO SEMANAL</div>{days.map((d,i)=><div className={i===0?'today':''}><span>{d.split(' ')[0]}</span><b>{d.split(' ')[1]}</b></div>)}</div><div className="weekGrid"><div className="teams"><b>Mecânica</b><b>Elétrica</b><b>Instrumentação</b><b>Operação</b></div>{days.map((_,day)=><div className="dayCol">{day<4&&<div className={`job j${day}`} style={{marginTop:day===2?100:day===1?195:15}}><small>{day===0?'08:00–12:30':day===1?'13:00–16:00':'09:00–11:00'}</small><b>{orders[day].tag}</b><span>{orders[day].service}</span><div><i>{orders[day].owner.split(' ').map(x=>x[0]).join('')}</i><Priority value={orders[day].priority}/></div></div>}{day===0&&<div className="job j4"><small>14:00–16:00</small><b>LSH-224</b><span>Validação de calibração</span></div>}</div>)}</div></div></>}

function GenericPage({page}:{page:Page}){const data:any={indicators:['Indicadores de manutenção','Acompanhe performance, metas e tendências dos principais indicadores.'],reports:['Central de relatórios','Gere análises operacionais com dados consolidados e rastreáveis.'],alerts:['Central de alertas','Priorize desvios, riscos operacionais e ações críticas.'],users:['Usuários e acessos','Gerencie equipes, perfis e permissões de acesso.'],settings:['Configurações','Personalize unidades, fluxos, integrações e preferências.']};const [title,desc]=data[page];return <><PageIntro text={desc}><button className="secondary"><Download/> Exportar</button><button className="primary"><Plus/> {page==='users'?'Novo usuário':'Criar configuração'}</button></PageIntro>{page==='indicators'?<Indicators/>:page==='alerts'?<Alerts/>:<div className="genericGrid"><div className="card genericMain"><div className="emptyIcon">{page==='reports'?<FileBarChart/>:page==='users'?<Users/>:<Settings/>}</div><h2>{title}</h2><p>Este módulo já está integrado à navegação do protótipo e preparado para receber dados da API corporativa.</p><div className="featureRows">{['Visão consolidada por unidade e área','Filtros avançados e exportação','Histórico completo e auditável'].map(x=><div><Check/>{x}<ChevronRight/></div>)}</div></div><div className="card sideNote"><Zap/><h3>Pronto para integração</h3><p>Conecte a fonte de dados corporativa para ativar todas as funções deste módulo.</p><button className="secondary">Ver documentação</button></div></div>}</>}
function Indicators(){return <><div className="metrics indicatorMetrics"><Metric label="IAMOT" value="87,4" unit="%" delta="3,2%" icon={Activity}/><Metric label="Disponibilidade" value="94,8" unit="%" delta="2,4%" icon={Gauge}/><Metric label="MTBF" value="186" unit="h" delta="8,6%" icon={Timer}/><Metric label="MTTR" value="3,4" unit="h" delta="0,7h" good={false} icon={Wrench}/></div><div className="card panel bigTrend"><div className="panelHead"><div><h3>Evolução dos indicadores</h3><p>Realizado x meta · março a agosto</p></div><button className="secondary">Disponibilidade <ChevronDown/></button></div><TrendChart/></div></>}
function Alerts(){return <div className="alertsLayout"><div className="card alertList"><div className="alertFilters"><button className="active">Todos <i>12</i></button><button>Críticos <i>3</i></button><button>Atenção <i>5</i></button><button>Informativos <i>4</i></button></div>{[['Correia CT-07B parada','OM crítica atrasada há 4 horas','critical'],['MTTR acima da meta na britagem','Indicador aumentou 18% nos últimos 7 dias','warning'],['Preventivas próximas do vencimento','3 atividades vencem nas próximas 24 horas','warning'],['Estoque crítico de rolamento 22318','Saldo atual abaixo do estoque mínimo','critical'],['Sincronização concluída','18 apontamentos de campo sincronizados','info']].map(x=><div className={`fullAlert ${x[2]}`}><span>{x[2]==='critical'?<AlertTriangle/>:x[2]==='warning'?<Clock3/>:<Cloud/>}</span><div><h3>{x[0]}</h3><p>{x[1]}</p><small>Terminal Sudeste · há 24 minutos</small></div><button><MoreHorizontal/></button></div>)}</div><div className="card alertSummary"><h3>Resumo por severidade</h3><div className="severityRing"><div><b>12</b><span>ativos</span></div></div><p><i className="red"/>Crítico <b>3</b></p><p><i className="orange"/>Atenção <b>5</b></p><p><i className="blue"/>Informação <b>4</b></p></div></div>}

function AIPage(){const [query,setQuery]=useState('');const [answer,setAnswer]=useState(false);return <div className="aiPage"><div className="aiHero"><div className="aiOrb"><Bot/></div><span>IA DE MANUTENÇÃO</span><h2>Como posso apoiar sua operação?</h2><p>Analise indicadores, falhas, ordens e passagens de turno usando linguagem natural.</p><form onSubmit={e=>{e.preventDefault();if(query)setAnswer(true)}}><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pergunte sobre sua operação..."/><button><Sparkles/> Analisar</button></form><div className="suggestions">{['Quais ordens críticas estão atrasadas?','Resuma o turno da noite','Ativos com queda no MTBF'].map(x=><button onClick={()=>setQuery(x)}>{x}</button>)}</div></div>{answer&&<div className="card aiAnswer"><div><Sparkles/><b>Análise operacional</b><small>Gerado agora · baseado em dados do Terminal Sudeste</small></div><p>Encontrei <strong>2 ordens críticas atrasadas</strong>. A OM-2026-1552, da correia CT-07B, tem maior impacto operacional e está atrasada há 4 horas. Recomendo priorizar o alinhamento, validar o bloqueio de segurança e atualizar a previsão de retorno.</p><div className="answerActions"><button className="secondary">Ver ordens relacionadas</button><button><MessageSquareText/> Fazer outra pergunta</button></div></div>}</div>}

function FieldPage(){const [online,setOnline]=useState(false);return <><PageIntro text="Experiência móvel offline-first para execução segura em campo."><button className={`connection ${online?'online':''}`} onClick={()=>setOnline(!online)}>{online?<Cloud/>:<CloudOff/>}{online?'Online · sincronizado':'Offline · 3 pendências'}</button></PageIntro><div className="fieldLayout"><div className="phone"><div className="phoneTop"><span>09:41</span><b>● ● ●</b></div><div className="mobileHead"><Logo/><div className={online?'onlineDot':''}/></div><div className="mobileGreeting"><span>Olá, João</span><h2>Minhas ordens</h2></div><div className="mobileTabs"><button className="active">Todas <i>8</i></button><button>Em execução <i>2</i></button><button>Programadas <i>6</i></button></div><div className="mobileOrders">{orders.slice(0,3).map((o,i)=><div><span><Priority value={o.priority}/><Status>{o.status}</Status></span><b>{o.id}</b><h3>{o.tag} · {o.asset}</h3><p>{o.service}</p><small><Clock3/> {o.due}</small>{i===0&&<button>Continuar execução <ChevronRight/></button>}</div>)}</div><nav className="mobileNav"><button className="active"><Wrench/>Ordens</button><button><ClipboardCheck/>Apontar</button><button><Cloud/>Sincronizar<i>3</i></button><button><Users/>Perfil</button></nav></div><div className="fieldInfo"><span className="eyebrow">PWA PARA CAMPO</span><h2>Trabalho contínuo,<br/>mesmo sem conexão.</h2><p>Ordens, checklists, horas, materiais e evidências ficam disponíveis no dispositivo. Ao recuperar a conexão, tudo é sincronizado automaticamente.</p><div className="offlineFeatures"><div><CloudOff/><span><b>Offline-first</b>Dados disponíveis sem internet</span></div><div><ShieldCheck/><span><b>Sincronização segura</b>Tratamento inteligente de conflitos</span></div><div><Package/><span><b>Evidências completas</b>Fotos, arquivos e assinatura digital</span></div></div><div className="syncCard"><div><span>ÚLTIMA SINCRONIZAÇÃO</span><b>Hoje, 09:38</b></div><div><span>ITENS PENDENTES</span><b>3 registros</b></div><button onClick={()=>setOnline(true)}><Cloud/> Sincronizar agora</button></div></div></div></>}

export default function App(){const [page,setPage]=useState<Page>('dashboard');const [side,setSide]=useState(false);const content=useMemo(()=>{if(page==='dashboard')return <Dashboard setPage={setPage}/>;if(page==='orders')return <Orders/>;if(page==='assets')return <Assets/>;if(page==='handover')return <Handover/>;if(page==='schedule')return <Schedule/>;if(page==='ai')return <AIPage/>;if(page==='field')return <FieldPage/>;return <GenericPage page={page}/>},[page]);return <div className="app"><Sidebar page={page} setPage={setPage} open={side} setOpen={setSide}/><main><Header page={page} onMenu={()=>setSide(true)}/><div className="content">{content}</div><footer><span>Nexum Maintenance Hub · Ambiente de demonstração</span><span>v0.1.0 · Dados atualizados agora</span></footer></main>{side&&<div className="sideOverlay" onClick={()=>setSide(false)}/>}</div>}
